### PR TITLE
[WorkflowsApp] Fix and Switch to Elsa Studio

### PR DESCRIPTION
**Pull request by mohdali**
Elsa Dashboard (StencilJs based) is now deprecated. This PR updates to the latest Elsa Release and switches to the new Elsa Studio using Blazor Server.

Activity provider is also updated to generate the skills:

image

### CODE REVIEW

**Comment by mohdali** [comment]
I updated the activity properties definition and created a sample workflow which works correctly!

image
image

@rysweet @kostapetan can you please consider merging the updated code to the workflow app?

**Comment by mohdali** [comment]
Hi @kostapetan @crgarcia12, are you interested in this PR? I can help further improve the workflow sample once this is reviewed and merged.

**Comment by kostapetan** [comment]
> Hi @kostapetan @crgarcia12, are you interested in this PR? I can help further improve the workflow sample once this is reviewed and merged.

Hello @mohdali, thanks for taking the time to submit the PR!

Tiny bit of background and context, this repo started out as an exploration into an idea, to see how far we can get with a naive implementation of building a dev team with Semantic Kernel skills (hence the name of the repo 😅 ). We did a bunch of experiments, one of them being the Workflows project that used Elsa.

Fast forward to today, where our goal is to capture a framework and it's patterns for building event driven AI Agents (using Orleans/Dapr actors), we still haven't decided if the WorkflowsApp will be part of the samples or not.
We'll keep the PR open and come back to you once things crystallise a bit, I hope that is ok.

**Comment by mohdali** [comment]
@kostapetan sure! Thanks for thanks for the clarification.

**Comment by rysweet** [comment]
I think it doesn't hurt to go ahead and accept this since it fixes broken stuff and doesn't conflict with the agents stuff. THANK YOU

**Pull request merged**
